### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by obnoxiousish** [cole/aiosmtplib#245] opened 2024-02-01 09:57 UTC
If host isnt being used, server_hostname kwarg must be passed, so when you pass a sock and host=None, it always errors cuz no host= and no server_hostname=, only way to use passed sock is by patching smtp.py

please fix bro,, or if i create a pull request to natively support proxies will u accept or can u just do it urself using this

anyways,,,

Below is working example to use proxies with this libary.
For SSL to work properly must 

```
        if self.use_tls:
            tls_context = self._get_tls_context()
            ssl_handshake_timeout = timeout
            srvHostnameKwarg = {'server_hostname': self.local_hostname}
        else:
            srvHostnameKwarg = {'server_hostname': None}
```

and add "**srvHostnameKwarg" to create_connection in smtp.py

```
        if self.use_tls:
            tls_context = self._get_tls_context()
            ssl_handshake_timeout = timeout
            srvHostnameKwarg = {'server_hostname': self.local_hostname}
        else:
            srvHostnameKwarg = {'server_hostname': None}

        if self.sock is not None: # If we have a socket, do a create_connection on it
            connect_coro = self.loop.create_connection(
                lambda: protocol,
                sock=self.sock,
                ssl=tls_context,
                ssl_handshake_timeout=ssl_handshake_timeout,
                **srvHostnameKwarg
            )
        elif self.socket_path is not None:
            connect_coro = self.loop.create_unix_connection(
                lambda: protocol,
                path=self.socket_path,  # type: ignore
                ssl=tls_context,
                ssl_handshake_timeout=ssl_handshake_timeout,
                **srvHostnameKwarg
            )
        else:
            if self.hostname is None:
                raise RuntimeError("No hostname provided; default should have been set")
            if self.port is None:
                raise RuntimeError("No port provided; default should have been set")

            connect_coro = self.loop.create_connection(
                lambda: protocol,
                host=self.hostname,
                port=self.port,
                ssl=tls_context,
                ssl_handshake_timeout=ssl_handshake_timeout,
                local_addr=self.source_address,
                **srvHostnameKwarg
            )
```

Example:

```
  import asyncio
  from email.message import EmailMessage
  import aiosmtplib
  #from python_socks import ProxyType, Proxy
  from python_socks.async_.asyncio import Proxy
  
  async def send_email_via_proxy():
      # Initialize the proxy
      proxy = Proxy.from_url('socks5://127.0.0.1:43594')
      
      # Create a socket connected through the proxy
      sock = await proxy.connect(
          dest_host='outlook-namnorthwest2.office365.com', 
          dest_port=587
      )
      
      print(sock)
      
      # Prepare your email message
      message = EmailMessage()
      message["From"] = "FROM_EMAIL"
      message["To"] = "TO_EMAIL"
      message["Subject"] = "Hello from behind a proxy"
      message.set_content("This is a test email sent through a proxy server.")
      
      # Send the email using aiosmtplib with the connected socket
      results = await aiosmtplib.send(
          message,
          username='USERNAME',
          password='PASSWORD',
          sock=sock,
          #tls=True,
          hostname=None,
          port=None,
          socket_path=None,
      )
      
      print(results)
  
  # Run the async function
  asyncio.run(send_email_via_proxy())
```

**Comment by cole** [comment] 2024-02-14 03:23
I would accept a PR with tests for this change, if you'd like to integrate it.

Otherwise, there's a longstanding feature request, #19. Closing as a dupe of that.

**Closed by cole** 2024-02-14 03:23 UTC
Labels: 🐛 bug
